version: '3.7'

services:
  # MQTT Broker – Mosquitto
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"   # MQTT
      - "9001:9001"   # WebSocket (opcional)
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  # Node-RED
  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    restart: always
    ports:
      - "1880:1880"   # Dashboard Web
    volumes:
      - ./data:/data
    depends_on:
      - mosquitto
